### ISSUE TITLE
Ping Failed!

### ISSUE THREAD

**Issue by czhou** [atcol/docker-registry-ui#151]
I am running registry:2, seems the .../v2/_ping API does not exist at all, therefor I can't add any registry.
please refer this issue, it says that registry:2 uses /v2/ as ping endpoint, not /v2/_ping anymore.
https://github.com/docker/distribution/issues/994

**Comment by fernandoneto** [comment]
im getting the same problem. im running docker distribution and its impossible to add registry's.
@czhou i think the support for v2 is not available ate the moment. take a look at #141.

**Comment by bpiselli** [comment]
Yes _ping does not exists in v2 : "/" home route should be used here :
https://github.com/atc-/docker-registry-ui/blob/e79c9bbbce2a670376d49d22168762c80c52c1cd/grails-app/services/docker/registry/web/RepositoryService.groovy#L128

someone would like to improve it ?

**Comment by nenadalm** [comment]
should this work? I've tried `sudo docker run -d -p 8080:8080 atcol/docker-registry-ui` but I still have the issue.

**Comment by atcol** [comment]
This needs to be released, that's all. I'll do it over the next few days.

**Comment by nenadalm** [comment]
@atcol  I've tried to build image myself using `./build-deploy.sh` script but then I encountered ssl exception described here: https://github.com/atcol/docker-registry-ui/issues/159

**Comment by marten-cz** [comment]
@atcol How does it look like with the release?

**Comment by atcol** [comment]
I'm in the process of generalising the release process a bit so this can almost be automated. I will postpone the refactor & push this out tonight/tomorrow instead. Sorry for the delay.

**Comment by atcol** [comment]
I have updated the latest image on Docker hub. Please try & see if it's working for you.

**Comment by geostant** [comment]
I'm using 0.98.0 and still got failed ping

**Comment by atcol** [comment]
This will be resolved in #162 . Thanks for the help all. Releasing ASAP.
