### ISSUE TITLE
This registry is unreachable - Docker Registry V2 version

### ISSUE THREAD

**Issue by assistanz247** [atcol/docker-registry-ui#163]
Hi team,

When I tried to add the docker registry v2 it shows "This registry is unreachable" error.

![image](https://user-images.githubusercontent.com/28589934/34976027-99acc686-faba-11e7-8990-f3970728e136.png)

![image](https://user-images.githubusercontent.com/28589934/34976034-ab0ae214-faba-11e7-9f0d-9baa3d219de3.png)

Any ideas on this?

**Comment by atcol** [comment]
Yep! This is being fixed as part of #162
